// export const SET_SELECTED_FOLDERS = 'SET_SELECTED_FOLDERS';
export const SELECTED_ITEMS = 'SELECTED_ITEMS';
export const SELECT_ALL_FOLDERS = 'SELECT_ALL_FOLDERS';
export const SET_SELECTED_ITEMS_MODE = 'SET_SELECTED_ITEMS_MODE';
export const INVERSE_SELECTED_ITEMS = 'INVERSE_SELECTED_ITEMS';
export const TOGGLE_ITEMS_SELECTION = 'TOGGLE_ITEMS_SELECTION';
export const ADD_TO_SELECTED_ITEMS = 'ADD_TO_SELECTED_ITEMS';
export const CLEAR_SELECTED_ITEMS = 'CLEAR_SELECTED_ITEMS';