export const CUT_FOLDERS_TOBUFFER = 'CUT_FOLDERS_TOBUFFER';
export const RECOVERY_FOLDER = 'RECOVERY_FOLDER';
export const ADD_ITEMS_TO_BUFFER = 'ADD_ITEMS_TO_BUFFER';
export const COPY_ITEMS_TO_BUFFER = 'COPY_ITEMS_TO_BUFFER';
export const CLEAR_BUFFER = 'CLEAR_BUFFER';
export const ADD_ACTION_BUFFER = 'ADD_ACTION_BUFFER';