// FOLDERS
export const CREATE_FOLDER = "CREATE_FOLDER";
export const ADD_FOLDER = "ADD_FOLDER";
export const SET_LOADING = "SET_LOADING";
export const CHANGE_FOLDER = "CHANGE_FOLDER";
export const REMOVE_FOLDER = "REMOVE_FOLDER";
export const RENAME_FOLDER = "RENAME_FOLDER";
export const GO_BACK = "GO_BACK";

export const MOVE_FOLDER = 'MOVE_FOLDER';
export const PASTE_FOLDERS = 'PASTE_FOLDERS';
export const SET_SELECTED_FOLDERS = 'SET_SELECTED_FOLDERS';
export const INVERSE_SELECTED_FOLDERS = 'REVERSE_SELECTED_FOLDERS';
export const UNSET_SELECTED_FOLDERS = 'UNSET_SELECTED_FOLDERS';
export const SELECT_ALL_FOLDERS = 'SELECT_ALL_FOLDERS';

export const ADD_ITEM_TO_BUFFER = 'ADD_ITEM_TO_BUFFER';
export const CUT_FOLDERS_TOBUFFER = 'CUT_FOLDERS_TOBUFFER';
export const CLEAR_BUFFER = 'CLEAR_BUFFER';
export const ADD_TO_DELETED_FOLDERS = 'ADD_TO_DELETED_FOLDERS';
export const RECOVERY_FOLDER = 'RECOVERY_FOLDER';
export const TOGGLE_ITEMS_SELECTION = 'TOGGLE_ITEMS_SELECTION';
