// FOLDERS
export const CREATE_FOLDER = "CREATE_FOLDER";
export const ADD_FOLDER = "ADD_FOLDER";
export const SET_LOADING = "SET_LOADING";
export const CHANGE_FOLDER = "CHANGE_FOLDER";
export const REMOVE_FOLDER = "REMOVE_FOLDER";
export const RENAME_FOLDER = "RENAME_FOLDER";
export const GO_BACK = "GO_BACK";
export const MOVE_FOLDER = 'MOVE_FOLDER';
export const PASTE_FOLDERS = 'PASTE_FOLDERS';
export const ADD_TO_DELETED_FOLDERS = 'ADD_TO_DELETED_FOLDERS';
export const RECOVERY_FOLDER = 'RECOVERY_FOLDER';
