// FILES
export const CREATE_FILES = "CREATE_FILES";
export const ADD_FILES = "ADD_FILES";
export const REMOVE_FILE = 'REMOVE_FILE';
export const SET_FILE_DATA = "SET_FILE_DATA";
export const RENAME_FILE = 'RENAME_FILE';
// export const COPY_FILE = 'COPY_FILE';
export const MOVE_FILE = 'MOVE_FILE';
export const PASTE_FILES = 'PASTE_FILES';
export const SET_SELECTED_FILES = 'SET_SELECTED_FILES';
export const INVERSE_SELECTED_FILES = 'REVERSE_SELECTED_FILES';
export const UNSET_SELECTED_FILES = 'UNSET_SELECTED_FILES';
export const SELECT_ALL_FILES = 'SELECT_ALL_FILES';

export const COPY_FILES_TOBUFFER = 'COPY_FILES_TOBUFFER';
export const CUT_FILES_TOBUFFER = 'CUT_FILES_TOBUFFER';
export const CLEAR_FILES_TOBUFFER = 'CLEAR_FILES_TOBUFFER';
export const SET_LOADING = 'SET_LOADINGß';
